version: "3.9"

services:
    qrkhudos:
        container_name: qrkhudos
        image: qrkhudos
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"